import re

class Table:

    def __init__(self, matrix, row_split, col_split, transpose):
        if transpose:
            matrix = map(list, zip(*matrix))
        self.matrix = matrix
        self.row_split = row_split
        self.col_split = col_split

    def write(self):
        output = "%%%\n%%% Generated by csv2latex (https://github.com/aekh/csv2latex)\n%%%\n"
        if self.row_split is not None:
            output += "%%% row partition " + str(self.row_split) + "\n"
        if self.col_split is not None:
            output += "%%% column partition " + str(self.col_split) + "\n"
        if self.row_split is not None or self.col_split is not None:
            output += "%%%\n"
        for rows in self.matrix:
            output += " & ".join(rows)
            output += " \\\\\n"
        return output
